### ISSUE TITLE
Update of dropper backend api.

### ISSUE THREAD

**Issue by Andrei-Dolgolev** [bugout-dev/engine#159]
Drop detail screen:
1. Add status column and transaction hash column
2. Upload date we not store but can return latest updated_at from claimants table
3. Total claimant amount, total amount
4. Total claimed(amount of claimants, amount of claimed).

Drops cards page. 
1. Return total count and number of page(probably need everywhere)
2. Store cache of token type(probably).
3. Add more filters it can be work as spire search(we need tags for drops).
4. Search on title and description now can be done by sql like without propper search.

**Comment by zomglings** [comment]
Either done or won't fix.
