### ISSUE TITLE
Design Document: Dropper 0.2.0

### ISSUE THREAD

**Issue by zomglings** [bugout-dev/engine#164]
We have deployed 2 earlier versions (both called `Dropper`, versions `0.0.1` and `0.1.0`) of the dropper contract, both of which have been used by both Moonstream and by Crypto Unicorns. This document details what we have learned from these production operations, and our desired improvements to the Dropper implementation for `Dropper v0.2.0` .

### Moving to the EIP-2535 Diamond specification

**Status: Accepted**

Deploying the Dropper as an immutable contract means that, if we found a bug or a vulnerability in the implementation, we would have to first deploy a version of the contract that fixed the bug and then migrate all claims and tokens to the new contract.

On top of this, we would have to find a way to migrate all state about claimed drops to the new contract, which is no small task. It would either require us to remove all claimed drops from the whitelist in the API, or it would require us to explicitly rewrite data about claimed drops onto the blockchain through transactions on the new contract.

We have already seen instances with DropperV1 and DropperV2 in which we wanted to add non-trivial functionality to Droppers as our operational experience with these contracts grows. Expecting our customers to use contracts at different addresses every time is not practical or reasonable.

Since all of our upgradable contracts are implemented as EIP-2535 DELEGATECALL proxies, and since we have mature tooling for contracts implementing this standard, this is how we will implement `Dropper v0.2.0`.

**Who does this affect?**

Us, as maintainers of the `Dropper` contracts.

### Claim → Drop

**Status: Accepted**

Our naming is inconsistent and has proven to be confusing to developers. What is called a *Claim* on `Dropper` will be called a *Drop* on `Dropper v0.2.0`.

**Who does this affect?**

Developers who use our contracts and our APIs.

### Signing authority will be determined by ownership of a Terminus token

**Status: Accepted**

Currently, we set a signer for each claim by calling the `setSignerForClaim` method. This gives a *single* address the authority to sign off on claims for all claimants.

This introduces two difficulties:

1. In case the authorized signing account gets compromised, cycling the authorized signer on the dropper contract is very difficult.
2. Often, projects will want to give signing authority to multiple team members without requiring those team members to share a private key to the single signing account.

Moving to Terminus-based administration solves both these problems as whoever controls the pool for the Terminus admin token can burn a holder’s token if it deems that holder to be compromised. And multiple accounts can bear a Terminus token from that pool, representing their ability to authorize claimants for a drop.

**Who does this affect?**

Crypto Unicorns - they will be able to give access to and revoke access from community managers for short-lived promotions.

Us, as we no longer have to run signing servers, which are a huge liability for us in terms of security and risk.

#### Note

The signatures for the `claim` and `claimMessageHash` methods have to be modified to incorporate the `signer` as an argument.

### RequestID-based protection on claims

**Status: Accepted**

On `Dropper` a given claimant address can only claim tokens from a given claim/drop once. If a project wanted to give that claimant the same token as two rewards, they would have to create two distinct claims/drops on the contract and add that claimant onto both whitelists.

This is actually desirable behavior in most cases, but there are exceptions. When a project is dropping small numbers of tokens at high frequency (for example, experience points), they would prefer for a single address to be able to claim a drop multiple times without the operational overhead of creating new drops on the contract each time.

The signature on [the `claim` method](https://github.com/bugout-dev/engine/blob/e3587388dd6d9a22a584827cdab4d139e36e8a52/contracts/Dropper.sol#L208) is:

```bash
function claim(
        uint256 claimId,
        uint256 blockDeadline,
        uint256 amount,
        bytes memory signature
    ) external;
```

I propose changing the `claim` method on `Dropper v0.2.0` so that it has the following signature:

```bash
function claim(
        uint256 claimId,
        uint256 blockDeadline,
        uint256 amount,
				uint256 requestID,
        bytes memory signature
    ) external;
```

Here, the contract prevents double spending to the claimant, not at the level of the claim itself, but at the level of the `requestID` whose semantics are determined by the signer(s).

**Who does this affect?**

This feature is required for *Moonstream Reputation* to become a real thing.

Crypto-Guilds is waiting for it.

Crypto Unicorns have enquired about this possibility multiple times.

### Optional maximum cumulative amounts awarded (per drop, per user per drop)

**Status: Rejected** (too complex and not enough users are strongly asking for it)

Projects occasionally want to give less-trusted members of their team the ability to distribute tokens through a drop. In these situations, the projects would prefer to enforce two controls:

1. A maximum amount of tokens awarded as part of that drop (so that the authorized team members cannot drop a small amount of tokens to a large number of addresses).
2. A maximum amount of tokens awarded as part of that drop to any single address (so that the authorized team members cannot drop the entirety of their allocation to a single account).

**Who does this affect?**

Crypto Unicorns have asked about both of these things in relation to their Community team being able to drop to Discord users.

### Paywalled claims

**Status: Rejected** (too complex and not enough users asking for it)

Recently, several projects have asked us if they could use the `Dropper` contracts + API to handle token sales.

We could add this functionality by adding a new `paywalledClaim` method which requires users to cough up a payment in order to claim a drop.

This `paywalledClaim` method should be capable of accepting payments both in the native token of the blockchain (Ether, Matic, etc.) or in ERC20 tokens.

**Who does this affect?**

Viking Art has asked for this functionality in the context of an ERC721 mint.

Crypto-Guilds has asked for this functionality in the context of Terminus mints (of their badges).

### Additional drop types

Currently, the `Dropper` contract allows the following drop types:

1. `20` - ERC20 transfer (requires sufficient balance on `Dropper` contract)
2. `721` - ERC721 transfer (requires `Dropper` contract to have ownership, only applies to a single NFT)
3. `1155` - ERC1155 transfer (requires sufficient balance on `Dropper` contract)
4. `1` - Terminus/ERC1155 mint (requires minting permissions on ERC1155 contract).

There are a few drop types that we could consider adding:

- ERC20 transferFrom. This drop type would transfer from a preconfigured holder address and would require the holder to have set sufficient allowance to the `Dropper` contract.
**Status: Under Review**
- ERC1155 transferFrom. This drop type would transfer from a preconfigured holder address and would require the holder to have set sufficient allowance to the `Dropper` contract.
**Status: Under Review**
- ERC20 mint. This drop type would mint ERC20 tokens to the claimant and would require the `Dropper` contract to have minting rights on the ERC20 contract.
**Status: Under Review**
- ERC721 mint. This drop type would mint ERC721 tokens to the claimant and would require the `Dropper` contract to have minting rights on the ERC721 contract.
**Status: Rejected** (Dropper is working fine for now and we have seen users compose the existing drop types with other contracts -- e.g. Crypto Unicorns ERC20 which transfers an NFT. The ultimate implementation would be to support arbitrary parametrized calls to a contract.)

The only issue for the ERC20 and ERC721 mint drop types is that there is no standard interface for minting functionality on those token standards. This is also true for ERC1155, but we implemented drop type `1` specifically for Terminus contracts.

One alternative is to include a drop type that calls a contract at a given address with preconfigured call data. This would allow the `Dropper` to execute arbitrary code on the target contract for that drop type. This solution seems a bit dangerous.

**Comment by kompotkot** [comment]
Client signer new version https://github.com/bugout-dev/engine/issues/162

**Comment by kompotkot** [comment]
Detailed design with comments: https://docs.google.com/document/d/1Be_Ms01IiDXQUjXOi4ihHO-26K3nvh1mAV6mM2KStyo/edit#

**Comment by Andrei-Dolgolev** [comment]
Drawio diagram of current implementation of Dropper V1 workflow.
https://drive.google.com/file/d/1TkA7zERaIsL1gkKFkAkNd3KNrmQ_K_Kp/view?usp=sharing

**Comment by zomglings** [comment]
Needs a migration plan for existing Dropper contracts.

**Comment by kompotkot** [comment]
### Client signer

Schema specified in Issue https://github.com/bugout-dev/engine/issues/162
Required changes:
- Engine API `add_claimants` endpoint modification to be able to parse `signature` and `claim_block_deadline` from request for each claimant
- Update of Engine Frontend upload csv workflow

**Comment by zomglings** [comment]
0 as a default amount is also a bad idea. It makes auditing drops harder for whoever sends signatures, and it adds unnecessary complexity on the smart contract. We will get rid of it in this iteration.

**Comment by zomglings** [comment]
Updated plan now that we are revisiting Dropper 0.2.0.

# Dropper 0.2.0 Features

## From design document:

- [ ] Drops can be signed by anyone holding a specific Terminus token. Token is specified on a per-drop basis.
- [ ] Double spend prevented using (dropID, requestID) as key.
- [ ] No maximum cumulative amounts for drops - that simply makes logic more complex and it's not clear this
is needed.
- [ ] No default amounts on drops.
- [ ] No paywalled claims.

## From current implementation of DropperFacet:

- [ ] Remove `MaxClaimable` and `AmountClaimed` from `DropperStorage` - those are related to features we no logner want.
- [ ] Remove `_maxClaimable` on `createDrop`.
- [ ] Add methods to register Terminus admin badge per drop. Add `AdminTerminusAddress` and `AdminTerminusPoolID` to `DropperStorage`. Accept `signerAddress` argument on `claim` and `claimMessageHash`.

**Comment by zomglings** [comment]
> 0 as a default amount is also a bad idea. It makes auditing drops harder for whoever sends signatures, and it adds unnecessary complexity on the smart contract. We will get rid of it in this iteration.

Also nobody ever used them.
